### ISSUE TITLE
VirtualDub Portable Plugins Pack missing from repo

### ISSUE THREAD

**Issue by MailYouLater** [PortableApps/AppConfigs#7]
The VirtualDub Portable Plugins Pack appconfig is missing from this repo.

Also, separate, but related.  The [VirtualDub Portable](https://portableapps.com/apps/music_video/virtualdub_portable) page on PortableApps.com has a "More info." link that points to http://fcchandler.home.comcast.net/~fcchandler/index.html, which has apparently been a dead link since 2012.
Most recent archived version I could find is http://web.archive.org/web/20120905231420/http://fcchandler.home.comcast.net/~fcchandler/index.html

**Comment by JohnTHaller** [comment]
Added with [commit e19cac0a48940fcc4b345e76fcc1a35d3e1bab75](https://github.com/PortableApps/AppConfigs/commit/e19cac0a48940fcc4b345e76fcc1a35d3e1bab75)

Homepage fixed
