### ISSUE TITLE
Issue with Opera GX portable launcher

### ISSUE THREAD

**Issue by Andrew-J-Larson** [PortableApps/AppConfigs#9]
While I've noticed this on Opera GX, it may affect the other Opera versions you have made portable app versions for.

Steps:
1. Have the Rockstar launcher installed and running (notice, this runs as `Launcher.exe` in task manager).
2. Download, extract, and open Opera GX.

Expected behavior:
Should open fine.

Actual Behavior:
Says that Opera GX has already been launched (is falsely detecting the Rockstar Launcher as being Opera GX).

**Comment by JohnTHaller** [comment]
You can alter the first section in the OperaGXPortable.ini file within OperaGXPortable\App\AppInfo\Launcher to read as follows:

[Launch]
ProgramExecutable=OperaGX\opera.exe
WorkingDirectory=%PAL:AppDir%\OperaGX
CommandLineArguments=--user-data-dir="%PAL:DataDir%\profile\data"
WaitForEXE1=installer.exe
WaitForEXE2=opera_autoupdate.exe
WaitForEXE3=opera_crashreporter.exe
WaitForEXE4=wow_helper.exe
DirectoryMoveOK=yes
SupportsUNC=yes
MinOS=7

This should accomplish the desired result for you. Mainline Opera Portable is already doing this.

**Comment by Andrew-J-Larson** [comment]
> You can alter the first section in the OperaGXPortable.ini file within OperaGXPortable\App\AppInfo\Launcher to read as follows:
> 
> [Launch] ProgramExecutable=OperaGX\opera.exe WorkingDirectory=%PAL:AppDir%\OperaGX CommandLineArguments=--user-data-dir="%PAL:DataDir%\profile\data" WaitForEXE1=installer.exe WaitForEXE2=opera_autoupdate.exe WaitForEXE3=opera_crashreporter.exe WaitForEXE4=wow_helper.exe DirectoryMoveOK=yes SupportsUNC=yes MinOS=7
> 
> This should accomplish the desired result for you. Mainline Opera Portable is already doing this.

A little confused here, but it appears that the first section of both appear the same for the Opera versions (disregarding a slight path change).

Does what you say mean that the settings have not yet been up streamed to the portable app after the 3 years it's been up, or am I missing something?

**Comment by JohnTHaller** [comment]
The modified version I pasted above leaves out launcher.exe entirely. The current Opera GX Portable launcher both on github and in the release is as follows:

[Launch]
ProgramExecutable=OperaGX\launcher.exe
WorkingDirectory=%PAL:AppDir%\OperaGX
CommandLineArguments=--user-data-dir="%PAL:DataDir%\profile\data"
WaitForEXE1=installer.exe
WaitForEXE2=opera.exe
WaitForEXE3=opera_autoupdate.exe
WaitForEXE4=opera_crashreporter.exe
WaitForEXE5=wow_helper.exe
DirectoryMoveOK=yes
SupportsUNC=yes
MinOS=7

**Comment by JohnTHaller** [comment]
This is fixed in today's release of 109.0.5097.62
